export default [
  {
    title: 'TicketsPass',
    url: 'https://ticketspass.vercel.app/',
    src: '/images/ticketspass-preview.png',
    description:
      'ticketspass_desc',
    tools: [
      'React',
      'Express',
      'MongoDB',
      'React Native',
      'Mongoose',
      'Passport',
      'JWT Token',
      'i18Next',
      'Redux',
      'MercadoPago',
      'Bootstrap',
      'Formik'
    ],
    icon: '🎫',
  },
  {
    title: 'MyTinerary',
    url: 'https://mytineraryteamperro.vercel.app/',
    src: '/images/mytinerary-preview.png',
    description:
      'mytinerary_desc',
    tools: [
      'React',
      'Express',
      'MongoDB',
      'React Native',
      'Mongoose',
      'Passport',
      'JWT Token',
      'Redux',
    ],
    icon: '✈️',
  },
  {
    title: 'Pomodoro',
    url: 'https://ivangutierrez92.github.io/pomodoro/',
    src: '/images/pomodoro-preview.png',
    description:
      'pomodoro_desc',
    tools: [
      'React',
      'NextJS',
      'PWA',
      'Local storage',
      'Flexbox',
      'Sass',
      'Formik',
      'Yup',
      'FontAwesome',
    ],
    icon: '🍅',
  },
  {
    title: 'Where in the world',
    url: 'https://ivangutierrez92.github.io/where-in-the-world/',
    src: '/images/whereintheworld-preview.png',
    description:
      'world_desc',
    tools: [
      'React',
      'NextJS',
      'REST API',
      'Local storage',
      'Dark Mode',
      'Flexbox',
      'CSS Grid',
      'react-select',
    ],
    icon: '🌎',
  },
  {
    title: 'photo_port',
    url: 'https://ivangutierrez92.github.io/fotollama/',
    src: '/images/fotollama-preview.png',
    description: 'photo_port_desc',
    tools: ['React', 'NextJS', 'Framer Motion', 'Flexbox', 'Grid', 'react-responsive'],
    icon: '📷',
  },
];
